persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# Port 1883 tetap dibuka untuk koneksi lokal (non-websocket)
listener 1883
allow_anonymous true

# Port 9001 khusus untuk Websocket (yang ditarget oleh Cloudflare)
listener 9001
protocol websockets
allow_anonymous true
